### ISSUE TITLE
How to configure MQTT to HomeAssistant Mosquitto

### ISSUE THREAD

**Issue by buijsp** [melkati/CO2-Gadget#100]
Seems not to connect
Initializing MQTT to broker IP: 192.168.100.36
                                                                 -->[MQTT] Attempting MQTT connection...  not possible to connect to 192.168.100.36 Connection status:  5. (22 of 12                                   retries)
         -->[MQTT] Max retries to connect to MQTT broker reached, disabling MQTT...

**Comment by melkati** [comment]
Your broker is rejecting the connection.
