### ISSUE TITLE
Ability to configure gadget through web interface

### ISSUE THREAD

**Issue by hapklaar** [melkati/CO2-Gadget#112]
Would be cool if the device could be configured via the web interface. Feel free to close if you're not interested.

**Comment by melkati** [comment]
It's in the works.

It's on what I was working on for the last few days:

![CO2 Gadget Web Preferences](https://github.com/melkati/CO2-Gadget/assets/11509521/c91b095f-9c10-491b-9b97-0a8ccd1cd312)

**Comment by melkati** [comment]
Dup #44

**Comment by melkati** [comment]
First working version merged into master
