### ISSUE TITLE
WiFi Settings over BLE doesn't work if WiFi is dissabled 

### ISSUE THREAD

**Issue by melkati** [melkati/CO2-Gadget#132]
From @Coscolin:

_It's not a question of rebooting... If you enter SSID and pass from the mobile, when the gadget is set to WiFi=OFF, it doesn't work. In reality it does nothing, because the SSID values are not filled in the gadget, when you enter the menu it is blank, and when you activate WiFi from the gadget menu I imagine it tries to connect to WiFi with the values that are in the gadget (which are blank)... Once WiFi is activated in the gadget, even if it could not connect because SSID and pass were wrong, if you configure those values from the mobile, it connects without the need to reboot or anything else._

_The curious thing is that once connected to WiFi, you enter the gadget's menu and SSID is still blank, although the connection is fine and active._

_When you turn off the gadget and turn it on again, it does not reconnect to the WiFi, as it does not have the values saved, you have to start again._

**Comment by melkati** [comment]
Checked!

Preferences are not saved.

Also, decide if after setting credentials WiFi must be activated if not active or let the user decide.

**Comment by melkati** [comment]
I think the problem was because I missed to activate Wifi after a successful Wifi changed via BLE.

I'll apply the fix in the next release version.

Please, test if it's solved for you. I close this issue for now. I will open it again if you say it's not solved.

Thank you.

**Comment by Coscolin** [comment]
I've tested it and it works.

Thank you very much.
