### ISSUE TITLE
Duplicate definition batteryVoltageNow=0

### ISSUE THREAD

**Issue by Coscolin** [melkati/CO2-Gadget#194]
batteryVoltageNow is defined twice, in line:
https://github.com/melkati/CO2-Gadget/blob/d453c333f8b960fb195a7c3325119167b16ba4ba/CO2_Gadget_Battery.h#L70

and inside readBatteryVoltage() funcion:
void readBatteryVoltage() {
    float batteryVoltageNow = 0;

**Comment by melkati** [comment]
Thank you. Fixed in development!
It was an unused variable. Leftover code.
