### ISSUE TITLE
It's not neccesary read CPU frecuency in each loop

### ISSUE THREAD

**Issue by Coscolin** [melkati/CO2-Gadget#195]
I think is better to move this line to setup() function
https://github.com/melkati/CO2-Gadget/blob/95fcd60b3a61de60b62eaf9759ea59b708952b85/CO2_Gadget.ino#L557

and change value inside setCpuFrequencyAndReinitSerial() function

**Comment by melkati** [comment]
Will revisit it after we have the low power version ready.
