### ISSUE TITLE
Auto detect SSID WIFI access points

### ISSUE THREAD

**Issue by Coscolin** [melkati/CO2-Gadget#36]
Show in a list available SSID and select one to connect.

**Comment by freddujour** [comment]
Would be great also if in an instable wifi environment, the gadget would try the reconnect  to the AP in case the link is lost (including the MQTT broker). At this moment both are going to off.

**Comment by melkati** [comment]
> Would be great also if in an instable wifi environment, the gadget would try the reconnect to the AP in case the link is lost (including the MQTT broker). At this moment both are going to off.

Hi @freddujour 

Thanks for your suggestion.

I can do it but, please, open your own feature request so it doesn't get mixed with the one to list available SSID.

**Comment by freddujour** [comment]
Sorry, done. You can delete my comment.
Thanks for the great job

**Comment by melkati** [comment]
Thank you. Follows at #89
