### ISSUE TITLE
Add SenseAir Sunrise CO2 sensor

### ISSUE THREAD

**Issue by erguro1973** [melkati/CO2-Gadget#59]
It will be great if SenseAir Sunrise CO2 sensor will be available to the project
Thanks in advance

**Comment by melkati** [comment]
Hi. Thank you for suggestion.

CO2 Gadget is not an ultra low power monitor. It makes little sense to have a ultra low power sensor next to a non low power hardware and firmware.

As you already know there is another ultra low power monitor project with support for Senseair Sunrise CO2 sensor that will be public some day but... first we need to sort out the shortage of the Senseair Sunrise CO2 sensor and difficulty to buy other ultra low power sensors (like the Cubic CM1106SL-NS).

Senseair already told they are planing to release a new ultra low power monitor at the begging of the yr 2022.

Anyway, may be some day it becomes supported if it's included in sensorslib library.

You can find some more information regarding this topic at: #39
