### ISSUE TITLE
Changes

### ISSUE THREAD

**Issue by ljrnjh1964** [melkati/CO2-Gadget#74]
Hello. Please output the СO2 signals to separate pins for green, orange and red.

**Comment by melkati** [comment]
Hi

Please, can you develop your request a little more?

There are already individual pin outputs for green, orange and red. 

What do you want to accomplish?

**Comment by ljrnjh1964** [comment]
Hello. I need separate pins for orange and red for separate connection of the relay, the contacts of which close the capacitor leads to control the fan speed. You have orange and red at 32 pins. 
![Буфер обмена01](https://user-images.githubusercontent.com/92762458/147939390-2a1e1ee9-394b-44b7-9857-52969c557eb7.jpg)

**Comment by melkati** [comment]
Hi,

Sorry, my mistake. It was an error on documentation.  Orange is on pin 32 and red in 33

https://github.com/melkati/CO2-Gadget/blob/d69294294bdaa790c71a2eee84285cf9e1bac1d1/platformio.ini#L60-L68

**Comment by ljrnjh1964** [comment]
Thanks a lot for the clarification.
