### ISSUE TITLE
WIFI password length limit

### ISSUE THREAD

**Issue by zorg2015** [melkati/CO2-Gadget#86]
HI,
I have build a CO2 sensor using the CO2 Gadget from mariete. It works fine in its standalone configuration. Now I would like to activate the wifi. unfortunately, it seems that the length of the password is limited to 28 characters whereas my wifi password uses 37 cars.  Do you confirm this limit ? If yes is it possible to increase this length ?

Regards

**Comment by melkati** [comment]
Hi.

Thank you for reporting this.

Yes, the actual max password length is around 30 characters. 

I will increase the length as to the maximum password length standard that allows a max length of 63 characters.

I hope to have this fix ready very soon.

Best regards.

**Comment by melkati** [comment]
Sorry for the delay. I'm working on this but I'm facing an issue while modifying the menu.

I'm awaiting for an answer from the menu's library author.

#https://github.com/neu-rah/ArduinoMenu/issues/378

**Comment by zorg2015** [comment]
Thank you for having taken into account my request. I didn't think it would be necessary to modify a library but it seems rather logical. So, I think it'll be simpler for me to shorten my password even if I have many wifi devices...
Have a nice day

**Comment by melkati** [comment]
I'm sorry fixing the menu is not in my hands right now.
I'll revisit this in the future to give a solution.
