### ISSUE TITLE
Trying to add a BME280 to my CO2 gadget with MH-Z19B

### ISSUE THREAD

**Issue by hapklaar** [melkati/CO2-Gadget#91]
First of all thank for your work on this. I love the project!

I'm not sure if this should be a feature request or if this should already work. I've built the CO2 gadget and really love it. I'm using it with a MH-Z19B sensor together with an 18650 in a case I found somewhere and it works fantastic.

I would like to add a BME280 sensor for temp/humidity/air pressure measurement, but haven't been able to get it working yet. From the documentation it wasn't clear to me if this should be possible with the precompiled firmware, so I just tried.

I've connected it to the i2c bus at pins 21/22 and to the 3.3v output of the T-Display, but it doesn't seem to get detected when checking the console output. (also tried swapping 21 and 22 as I wasn't sure which one was SDA and SCL)

Can you enlighten me on how to proceed?

**Comment by melkati** [comment]
Hi.

Sorry for late reply.

This combination should work without the need for modification or compilation. It was already tested.

Pay attention to wiring.
