### ISSUE TITLE
'Test functionality double click' notification pops up when clicking fast on navigate down button in menu

### ISSUE THREAD

**Issue by hapklaar** [melkati/CO2-Gadget#92]
When I navigate the menu and click twice a bit fast on the bottom button, a notification windows appears with text "Test functionality double click" and doesn't disappear.

This is likely left over code from some test, but it interferes with menu navigation.

**Comment by hapklaar** [comment]
If anyone else is looking for this, fix is pretty easy, just comment lines 16-21 and 41 in CO2_Gadget_Buttons.h

**Comment by melkati** [comment]
Hi.

Yes it's code left from some testing for future new features still pending to finish implementation. Didn't had enough time lately.
