### ISSUE TITLE
Add support for ESP32-C3

### ISSUE THREAD

**Issue by errolt** [melkati/CO2-Gadget#94]
**Is your feature request related to a problem? Please describe.**
Please add support for esp32-c3 cpu.

**Describe the solution you'd like**
To be able to compile for the esp32-c3

**Describe alternatives you've considered**
I have tried to modify the code, but the code, and libs that are used, assume that all esp32 cpus have serial2, which the esp32-c3 doesn't.
Even though I am able to compile the code, I can't get it running. Don't know what is wrong.

**Comment by melkati** [comment]
I don't have an ESP32 C3 for testing so I can't include support for it.

Anyway, I'm not sure if there is a point in including support for this "reduced" chip.

CO2 Gadget has many features and had problems with memory in the past and ESP32 C3 has less memory than other ESP32 chips so it can be a stopper for further developing.
