### ISSUE TITLE
SSH support

### ISSUE THREAD

**Issue by buijsp** [melkati/CO2-Gadget#99]
When installed it is not always easy to reach the panel or USB interface to change the configuration.
Is it possible to implement SSH to be able to configure over the WiFi connection?

**Comment by melkati** [comment]
There are no plans to implement SSH support but you can see in roadmap web configuration is planned and will, probably, be supported someday.

https://github.com/melkati/CO2-Gadget/projects/2#card-73284600

**Comment by buijsp** [comment]
Thanks good to know ;-)
